# Generated by Django 3.1.2 on 2020-10-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cht_name', models.TextField()),
                ('eng_name', models.TextField()),
                ('expectation', models.TextField()),
                ('poster_url', models.URLField()),
                ('release_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
